crm/config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('crm.urls', 'crm'), namespace='crm')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/crm/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', login, name='login'),
    path('logout', logout, name='logout'),
    
    
    path('dashboard', dashboard, name='dashboard'),
    path('dashbaord/contacts', dashboardContacts, name='dashboard-contacts'),
    path('dashbaord/invoices', dashboardInvoices, name='dashboard-invoices'),
    path('dashbaord/quotes', dashboardQuotes, name='dashboard-quotes'),
    path('dashbaord/statistics', dashboardStatistics, name='dashboard-statistics'),
    path('dashbaord/monthlysale', dashboardMonthlySale, name='dashboard-monthlysale'),
    
    
    path('profile', profile, name='profile'),
    
    
    path('staff', users, name='staff-users'),
    path('staff/add', addUser, name='add-staff-user'),
    path('staff/update/<int:id>', updateUser, name='update-staff-user'),
    path('staff/delete/<int:id>', deleteUser, name='delete-staff-user'),
    
    
    path('roles', roles, name='roles'),
    path('role/add', addRole, name='add-role'),
    path('role/update/<int:id>', updateRole, name='update-role'),
    path('role/delete/<int:id>', deleteRole, name='delete-role'),
    
    
    path('category/company', companyCategories, name='company-categories'),
    path('category/company/update/<int:pk>', updateCompanyCategory, name='update-company-category'),
    path('category/company/delete/<int:pk>', deleteCompanyCategory, name='delete-company-category'),
    
    
    path('category/event', eventCategories, name='event-categories'),
    path('category/event/update/<int:pk>', updateEventCategory, name='update-event-category'),
    path('category/event/delete/<int:pk>', deleteEventCategory, name='delete-event-category'),
    
    
    path('companies', companies, name='companies'),
    path('company/add', addCompany, name='add-company'),
    path('company/update/<int:pk>', updateCompany, name='update-company'),
    path('company/delete/<int:pk>', deleteCompany, name='delete-company'),
    
    
    path('contacts', contacts, name='contacts'),
    path('contact/add', addContact, name='add-contact'),
    path('contact/update/<int:pk>', updateContact, name='update-contact'),
    path('contact/delete/<int:pk>', deleteContact, name='delete-contact'),
    
    
    path('circles', circles, name='circles'),
    path('circle/update/<int:pk>', updateCircle, name='update-circle'),
    path('circle/delete/<int:pk>', deleteCircle, name='delete-circle'),
    
    
    path('events', events, name='events'),
    path('event/add', addEvent, name='add-event'),
    path('event/update/<int:pk>', updateEvent, name='update-event'),
    path('event/delete/<int:pk>', deleteEvent, name='delete-event'),
    
    
    path('inbox' , inbox, name='inbox'),
    path('messages/view' , viewMessageAjax, name='view-message'),
    path('messages/sent' , messagesSent, name='sent-messages'),
    path('messages/signatures' , messagesSignature, name='signature-messages'),
    path('messages/trash' , messagesTrash, name='trash-messages'),
    path('message/send' , sendMessage, name='send-message'),
    path('message/delete/<int:pk>' , deleteMessage, name='delete-message'),
    
    
    path('items', items, name='items'),
    path('item/add', addItem, name='add-item'),
    path('item/update/<int:pk>', updateItem, name='update-item'),
    path('item/delete/<int:pk>', deleteItem, name='delete-item'),
    
    
    path('taxes', taxes, name='taxes'),
    path('tax/add', addTax, name='add-tax'),
    path('tax/update/<int:pk>', updateTax, name='update-tax'),
    path('tax/delete/<int:pk>', deleteTax, name='delete-tax'),
    
    
    path('discounts', discounts, name='discounts'),
    path('discount/add', addDiscount, name='add-discount'),
    path('discount/update/<int:pk>', updateDiscount, name='update-discount'),
    path('discount/delete/<int:pk>', deleteDiscount, name='delete-discount'),
    
    
    path('invoice-settings', invoiceSetting, name='invoice-setting'),
    
    path('invoices', invoices, name='invoices'),
    path('invoice/add', addInvoice, name='add-invoice'),
    path('invoice/view/<str:inv_no>', viewInvoice, name='view-invoice'),
    path('invoice/delete/<int:id>', deleteInvoice, name='delete-invoice'),
    
    
    path('estimate-settings', estimateSetting, name='estimate-setting'),
    
    
    path('estimates', estimates, name='estimates'),
    path('estimate/add', addEstimate, name='add-estimate'),
    path('estimate/view/<str:est_no>', viewEstimate, name='view-estimate'),
    path('estimate/delete/<int:id>', deleteEstimate, name='delete-estimate'),
    
    
    path('templates', templates, name='templates'),
    path('template/add', addTemplate, name='add-template'),
    path('template/view/<int:pk>', viewTemplate, name='view-template'),
    path('template/update/<int:pk>', updateTemplate, name='update-template'),
    path('template/delete/<int:pk>', deleteTemplate, name='delete-template'),
    
    
    path('documents', documents, name='documents'),
    path('document/add', addDocument, name='add-document'),
    path('document/view/<int:pk>', viewDocument, name='view-document'),
    path('document/update/<int:pk>', updateDocument, name='update-document'),
    path('document/delete/<int:pk>', deleteDocument, name='delete-document'),
]

crm/templates/dashboard.html
{% extends 'base.html' %} {% load static %} {% load custom_tags %}

{% block title %} Dashboard {% endblock title %}


{% block body %}

<!-- Start Content-->
<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert" style="border-radius: 50px">
        <strong>{{message}}</strong>
    </div>
    {% endfor %}

    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card-box widget-user">
                <div class="text-center">
                    <h2 class="font-weight-normal text-primary" data-plugin="counterup">{% total_invoices %}</h2>
                    <h5>Invoices</h5>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6">
            <div class="card-box widget-user">
                <div class="text-center">
                    <h2 class="font-weight-normal text-pink" data-plugin="counterup">{% total_quotes %}</h2>
                    <h5>Quotations</h5>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6">
            <div class="card-box widget-user">
                <div class="text-center">
                    <h2 class="font-weight-normal text-info" data-plugin="counterup">{% total_clients %}</h2>
                    <h5>Clients</h5>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6">
            <div class="card-box widget-user">
                <div class="text-center">
                    <h2 class="font-weight-normal text-warning">$<span
                            data-plugin="counterup">{% total_revenue %}</span></h2>
                    <h5>Revenue</h5>
                </div>
            </div>
        </div>
    </div>


    <div class="row">

        <div class="col-xl-6">
            <div class="card-box">
                <h4 class="header-title mt-0">Statistics</h4>

                <div class="text-center" id="preloader1">
                    <lord-icon
                        src="https://cdn.lordicon.com/ymrqtsej.json"
                        trigger="hover"
                        style="width:250;height:250">
                    </lord-icon>
                </div>


                <canvas id="Statistics"></canvas>
                
                <script>

                    $(document).ready(function(){


                        $.ajax({
                            url : "{% url 'crm:dashboard-statistics' %}",
                            success:function(data){
                                $('#preloader1').hide()
                                // Sample data for the bar chart
                                var data = {
                                    labels: data.years,
                                    datasets: [{
                                        label: 'Sales',
                                        data: data.totals,
                                        backgroundColor: 'rgba(54, 162, 235, 0.7)', // Blue bars with alpha (transparency)
                                        borderColor: 'rgba(54, 162, 235, 1)', // Solid blue border
                                        borderWidth: 1
                                    }]
                                };

                                // Bar chart options
                                var options = {
                                    scales: {
                                        y: {
                                            beginAtZero: true
                                        },
                                    },
                                };

                                // Get the bar chart canvas element
                                var ctx = document.getElementById('Statistics').getContext('2d');

                                // Create the bar chart
                                var myBarChart = new Chart(ctx, {
                                    type: 'bar',
                                    data: data,
                                    options: options
                                });


                            }
                        })



                    })

                </script>
            </div>
        </div>

        <div class="col-xl-6">
            <div class="card-box">
                <h4 class="header-title mt-0">Total Revenue of {% now 'Y' %}</h4>

                <div class="text-center" id="preloader2">
                    <lord-icon
                        src="https://cdn.lordicon.com/ymrqtsej.json"
                        trigger="hover"
                        style="width:250;height:250">
                    </lord-icon>
                </div>

                
                <canvas id="monthlySale"></canvas>
                <script>

                    $(document).ready(function(){


                        $.ajax({

                            url : "{% url 'crm:dashboard-monthlysale' %}",

                            success:function(data){

                                $('#preloader2').hide()

                                // Sample data for the line chart
                                var data = {
                                    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
                                        'September', 'October', 'November', 'December'
                                    ],
                                    datasets: [{
                                        label: 'Sales',
                                        data: data.totals,
                                        borderColor: 'rgba(75, 192, 192, 1)', // Line color
                                        borderWidth: 2,
                                        fill: false // Do not fill the area under the line
                                    }]
                                };

                                // Line chart options
                                var options = {
                                    scales: {
                                        x: {
                                            title: {
                                                display: true,
                                                text: 'Months'
                                            }
                                        },
                                        y: {
                                            title: {
                                                display: true,
                                                text: 'Data'
                                            }
                                        },
                                    },
                                };

                                // Get the line chart canvas element
                                var ctx = document.getElementById('monthlySale').getContext('2d');

                                // Create the line chart
                                var myLineChart = new Chart(ctx, {
                                    type: 'line',
                                    data: data,
                                    options: options,
                                });

                            }

                        })

                    })
                    
                </script>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-xl-6">
            <div class="card-box">
                <div class="d-flex justify-content-between mb-2">
                    <h4 class="header-title ">Recent Quotes</h4>
                    <a href="{% url 'crm:estimates' %}">See all</a>
                </div>
    
                <div id="quotes"> 

                    <div class="text-center">
                        <lord-icon
                            src="https://cdn.lordicon.com/ymrqtsej.json"
                            trigger="hover"
                            style="width:250;height:250">
                        </lord-icon>
                    </div>

                    <script>
                        $(document).ready(function () {
                            $.ajax({
                                url: "{% url 'crm:dashboard-quotes' %}",
    
                                success: function (data) {
                                    $('#quotes').html(data)
                                },
                            })
                        })
                    </script>
                </div>
    
            </div>
        </div>

        <div class="col-xl-6">
            <div class="card-box">
                <div class="d-flex justify-content-between mb-2">
                    <h4 class="header-title ">Recent Invoices</h4>
                    <a href="{% url 'crm:invoices' %}">See all</a>
                </div>
    
                <div id="invoices">
                    <div class="text-center">
                        <lord-icon
                            src="https://cdn.lordicon.com/ymrqtsej.json"
                            trigger="hover"
                            style="width:250;height:250">
                        </lord-icon>
                    </div>

                    <script>
                        $(document).ready(function () {
                            $.ajax({
                                url: "{% url 'crm:dashboard-invoices' %}",
    
                                success: function (data) {
                                    $('#invoices').html(data)
                                },
                            })
                        })
                    </script>
                </div>
    
            </div>
        </div>

        <div class="col-xl-8">
            <div class="card-box">
                <div class="d-flex justify-content-between mb-2">
                    <h4 class="header-title ">Contacts</h4>
                    <a href="{% url 'crm:contacts' %}">See all</a>
                </div>
    
                <div id="contacts">
                    <div class="text-center">
                        <lord-icon
                            src="https://cdn.lordicon.com/ymrqtsej.json"
                            trigger="hover"
                            style="width:250;height:250">
                        </lord-icon>
                    </div>

                    <script>
                        $(document).ready(function () {
                            $.ajax({
                                url: "{% url 'crm:dashboard-contacts' %}",
    
                                success: function (data) {
                                    $('#contacts').html(data)
                                },
                            })
                        })
                    </script>
                </div>
    
            </div>
        </div>

        <div class="col-xl-4">
            <div class="card-box">

                <h4 class="header-title mt-0">Invoices/Quotes</h4>


                <canvas id="quote_invoice_ratio"></canvas>

                {% quote_invoice_ratio as ratio %}
                <script>
                    // Sample data for the doughnut chart
                    var ratio = JSON.parse("{{ratio | safe}}")
                    console.log(typeof (ratio))
                    var data = {
                        labels: ['Quotes', 'Invoices'],
                        datasets: [{
                            data: ratio,
                            backgroundColor: ['#FF6384', '#36A2EB'],
                            hoverBackgroundColor: ['#FF6384', '#36A2EB']
                        }]
                    };

                    // Doughnut chart options
                    var options = {
                        cutoutPercentage: 70,
                        animation: {
                            animateScale: true
                        }
                    };

                    // Get the doughnut chart canvas element
                    var ctx = document.getElementById('quote_invoice_ratio').getContext('2d');

                    // Create the doughnut chart
                    var myDoughnutChart = new Chart(ctx, {
                        type: 'doughnut',
                        data: data,
                        options: options
                    });
                </script>

            </div>
        </div>

    </div>

</div>


{% endblock body %}

crm/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Log in | Sankofa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/logo-sm.png' %}">

    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-stylesheet" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-stylesheet" rel="stylesheet" type="text/css" />

</head>


<body class="authentication-bg">

    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="text-center">
                        <a href="#" class="logo mb-3">
                            <img src="{% static 'images/logo.png' %}" alt="" height="100" class="logo-light mx-auto">
                            <img src="{% static 'images/logo.png' %}" alt="" height="100" class="logo-dark mx-auto">
                        </a>
                    </div>
                    <div class="card">

                        <div class="card-body p-4">

                            <div class="text-center mb-4">
                                <h4 class="text-uppercase mt-0">Sign In</h4>
                            </div>
                            {% for message in messages %}
                            <div class="alert alert-{{message.tags}}" role="alert" style="border-radius: 50px">
                                <strong>{{message}}</strong>
                            </div>
                            {% endfor %}
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <label for="emailaddress">Username</label>
                                    <input class="form-control" type="text" name="username" id="username" required
                                        placeholder="Enter your username">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="password">Password</label>
                                    <input class="form-control" type="password" required id="password" name="password"
                                        placeholder="Enter your password">
                                </div>
                                {% if request.GET.next %}
                                <input type="hidden" name="next" value="{{request.GET.next}}">
                                {% endif %}

                                <div class="form-group mb-0 text-center">
                                    <button class="btn btn-primary btn-block" type="submit"> Log In </button>
                                </div>

                            </form>

                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->


    <!-- Vendor js -->
    <script src="{% static 'js/vendor.min.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'js/app.min.js' %}"></script>

</body>


</html>

crm/templates/profile.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Profile {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Profile</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>User Details</h4><br>
                    <p>All of the user details</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{user_form | crispy}}
                    {{profile_form | crispy}}
                </div>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:profile' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary" name="updateProfile">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </form>



    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Update Password</h4><br>
                    <p>User can reset his password from here</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{password_form | crispy}}
                </div>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:profile' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary" name="updatePassword">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

{% endblock body %}