crm/config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('crm.urls', 'crm'), namespace='crm')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/crm/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', login, name='login'),
    path('logout', logout, name='logout'),
    
    
    path('dashboard', dashboard, name='dashboard'),
    path('dashbaord/contacts', dashboardContacts, name='dashboard-contacts'),
    path('dashbaord/invoices', dashboardInvoices, name='dashboard-invoices'),
    path('dashbaord/quotes', dashboardQuotes, name='dashboard-quotes'),
    path('dashbaord/statistics', dashboardStatistics, name='dashboard-statistics'),
    path('dashbaord/monthlysale', dashboardMonthlySale, name='dashboard-monthlysale'),
    
    
    path('profile', profile, name='profile'),
    
    
    path('staff', users, name='staff-users'),
    path('staff/add', addUser, name='add-staff-user'),
    path('staff/update/<int:id>', updateUser, name='update-staff-user'),
    path('staff/delete/<int:id>', deleteUser, name='delete-staff-user'),
    
    
    path('roles', roles, name='roles'),
    path('role/add', addRole, name='add-role'),
    path('role/update/<int:id>', updateRole, name='update-role'),
    path('role/delete/<int:id>', deleteRole, name='delete-role'),
    
    
    path('category/company', companyCategories, name='company-categories'),
    path('category/company/update/<int:pk>', updateCompanyCategory, name='update-company-category'),
    path('category/company/delete/<int:pk>', deleteCompanyCategory, name='delete-company-category'),
    
    
    path('category/event', eventCategories, name='event-categories'),
    path('category/event/update/<int:pk>', updateEventCategory, name='update-event-category'),
    path('category/event/delete/<int:pk>', deleteEventCategory, name='delete-event-category'),
    
    
    path('companies', companies, name='companies'),
    path('company/add', addCompany, name='add-company'),
    path('company/update/<int:pk>', updateCompany, name='update-company'),
    path('company/delete/<int:pk>', deleteCompany, name='delete-company'),
    
    
    path('contacts', contacts, name='contacts'),
    path('contact/add', addContact, name='add-contact'),
    path('contact/update/<int:pk>', updateContact, name='update-contact'),
    path('contact/delete/<int:pk>', deleteContact, name='delete-contact'),
    
    
    path('circles', circles, name='circles'),
    path('circle/update/<int:pk>', updateCircle, name='update-circle'),
    path('circle/delete/<int:pk>', deleteCircle, name='delete-circle'),
    
    
    path('events', events, name='events'),
    path('event/add', addEvent, name='add-event'),
    path('event/update/<int:pk>', updateEvent, name='update-event'),
    path('event/delete/<int:pk>', deleteEvent, name='delete-event'),
    
    
    path('inbox' , inbox, name='inbox'),
    path('messages/view' , viewMessageAjax, name='view-message'),
    path('messages/sent' , messagesSent, name='sent-messages'),
    path('messages/signatures' , messagesSignature, name='signature-messages'),
    path('messages/trash' , messagesTrash, name='trash-messages'),
    path('message/send' , sendMessage, name='send-message'),
    path('message/delete/<int:pk>' , deleteMessage, name='delete-message'),
    
    
    path('items', items, name='items'),
    path('item/add', addItem, name='add-item'),
    path('item/update/<int:pk>', updateItem, name='update-item'),
    path('item/delete/<int:pk>', deleteItem, name='delete-item'),
    
    
    path('taxes', taxes, name='taxes'),
    path('tax/add', addTax, name='add-tax'),
    path('tax/update/<int:pk>', updateTax, name='update-tax'),
    path('tax/delete/<int:pk>', deleteTax, name='delete-tax'),
    
    
    path('discounts', discounts, name='discounts'),
    path('discount/add', addDiscount, name='add-discount'),
    path('discount/update/<int:pk>', updateDiscount, name='update-discount'),
    path('discount/delete/<int:pk>', deleteDiscount, name='delete-discount'),
    
    
    path('invoice-settings', invoiceSetting, name='invoice-setting'),
    
    path('invoices', invoices, name='invoices'),
    path('invoice/add', addInvoice, name='add-invoice'),
    path('invoice/view/<str:inv_no>', viewInvoice, name='view-invoice'),
    path('invoice/delete/<int:id>', deleteInvoice, name='delete-invoice'),
    
    
    path('estimate-settings', estimateSetting, name='estimate-setting'),
    
    
    path('estimates', estimates, name='estimates'),
    path('estimate/add', addEstimate, name='add-estimate'),
    path('estimate/view/<str:est_no>', viewEstimate, name='view-estimate'),
    path('estimate/delete/<int:id>', deleteEstimate, name='delete-estimate'),
    
    
    path('templates', templates, name='templates'),
    path('template/add', addTemplate, name='add-template'),
    path('template/view/<int:pk>', viewTemplate, name='view-template'),
    path('template/update/<int:pk>', updateTemplate, name='update-template'),
    path('template/delete/<int:pk>', deleteTemplate, name='delete-template'),
    
    
    path('documents', documents, name='documents'),
    path('document/add', addDocument, name='add-document'),
    path('document/view/<int:pk>', viewDocument, name='view-document'),
    path('document/update/<int:pk>', updateDocument, name='update-document'),
    path('document/delete/<int:pk>', deleteDocument, name='delete-document'),
]

crm/templates/documents/add-document.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Add Document {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Add Document</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Document Title</h4><br>
                    <p>Add document title</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Document Detail</h4><br>
                    <p>Add document detail</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.document_for | as_crispy_field}}
                    <div id="invoice" style="display: none">
                        {{form.invoice | as_crispy_field}}
                    </div>
                    <div id="estimate" style="display: none">
                        {{form.estimate | as_crispy_field}}
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Template</h4><br>
                    <p>Choose template for document</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="form-group">
                        <label for="">Template:</label>
                        <select class="form-control" name="template" id="template">
                            <option value=" ">---------</option>

                            {% for i in templates %}
                            <option value="{{i.body}}" data-body="{{i.body}}">{{i.title}}</option>
                            {% endfor %}

                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Body</h4><br>
                    <p>Document Body</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.body | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:templates' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script>
    $('#template').on('change', function () {
        CKEDITOR.instances['id_body'].setData($(this).val());
    });

    $('#id_document_for').on('change', function () {
        var id = $(this).val();

        console.log(id)

        if (id == 1) {
            $('#invoice').show()
            $('#estimate').hide()
        } else if (id == 2) {
            $('#estimate').show()
            $('#invoice').hide()
        }
    })
</script>

{% endblock body %}

crm/templates/documents/add-template.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Add Template {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Add Template</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Template Title</h4><br>
                    <p>Add template title</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Body</h4><br>
                    <p>Template Body</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.body | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:templates' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

{% endblock body %}

crm/templates/documents/documents.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Documents {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Documents</h2>
        </div>
    </div>

    <div class="card card-body">
        {% if perms.crm.add_document %}
        <div class="table-header">
            <a href="{% url 'crm:add-document' %}" class="btn btn-outline-primary mb-4 float-right"><i
                    class="fa fa-plus"></i>&nbsp Add
                New</a>
        </div>
        {% endif %}


        {% if documents|length %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th class="text-center">Options</th>
                    </tr>
                </thead>
                <tbody>

                    {% for i in documents %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'crm:view-document' i.id %}" class="text-dark">{{i.title}}</a></td>
                        <td class="text-center">
                            
                            {% if perms.crm.view_document %}
                            <a href="{% url 'crm:view-document' i.id %}" class="mr-1 text-primary"><i class="fa fa-eye"></i></a>
                            {% endif %}
                            {% if perms.crm.change_document %}
                            <a href="{% url 'crm:update-document' i.id %}" class="mr-1 text-success"><i class="fa fa-pencil"></i></a>
                            {% endif %}
                            {% if perms.crm.delete_document %}
                            <a href="{% url 'crm:delete-document' i.id %}" class="text-danger"><i class="fa fa-trash"></i></a>
                            {% endif %}

                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        {% else %}
        <div class="card-header text-center">
            <h4>No record found</h4>
        </div>
        {% endif %}

    </div>
</div>

{% endblock body %}

crm/templates/documents/templates.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Templates {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Templates</h2>
        </div>
    </div>

    <div class="card card-body">
        {% if perms.crm.add_template %}
        <div class="table-header">
            <a href="{% url 'crm:add-template' %}" class="btn btn-outline-primary mb-4 float-right"><i
                    class="fa fa-plus"></i>&nbsp Add
                New</a>
        </div>
        {% endif %}


        {% if templates|length %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th class="text-center">Options</th>
                    </tr>
                </thead>
                <tbody>

                    {% for i in templates %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'crm:view-template' i.id %}" class="text-dark">{{i.title}}</a></td>
                        <td class="text-center">

                            <a href="{% url 'crm:view-template' i.id %}" class="mr-1 text-primary"><i class="fa fa-eye"></i></a>

                            {% if perms.crm.change_template %}
                            <a href="{% url 'crm:update-template' i.id %}" class="mr-1 text-success"><i class="fa fa-pencil"></i></a>
                            {% endif %}
                            {% if perms.crm.delete_template %}
                            <a href="{% url 'crm:delete-template' i.id %}" class="text-danger"><i class="fa fa-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        {% else %}
        <div class="card-header text-center">
            <h4>No record found</h4>
        </div>
        {% endif %}

    </div>
</div>

{% endblock body %}

crm/templates/documents/update-document.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} {{instance.title}} {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">{{instance.title}}</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Document Title</h4><br>
                    <p>Add document title</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Document Detail</h4><br>
                    <p>Add document detail</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.document_for | as_crispy_field}}
                    <div id="invoice" style="display: none">
                        {{form.invoice | as_crispy_field}}
                    </div>
                    <div id="estimate" style="display: none">
                        {{form.estimate | as_crispy_field}}
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Template</h4><br>
                    <p>Choose template for document</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="form-group">
                        <label for="">Template:</label>
                        <select class="form-control" name="template" id="template">
                            <option value=" ">---------</option>

                            {% for i in templates %}
                            <option value="{{i.body}}" data-body="{{i.body}}">{{i.title}}</option>
                            {% endfor %}

                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Body</h4><br>
                    <p>Document Body</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.body | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:documents' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script>
    $('#template').on('change', function () {
        CKEDITOR.instances['id_body'].setData($(this).val());
    });

    $('#id_document_for').on('change', function () {
        var id = $(this).val();

        console.log(id)

        if (id == 1) {
            $('#invoice').show()
            $('#estimate').hide()
        } else if (id == 2) {
            $('#estimate').show()
            $('#invoice').hide()
        }
    })
</script>

{% endblock body %}

crm/templates/documents/update-template.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} {{instance.title}} {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">{{instance.title}}</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Template Title</h4><br>
                    <p>Add template title</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4">
                <div class="card-body">
                    <h4>Body</h4><br>
                    <p>Template Body</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.body | as_crispy_field}}
                </div>
            </div>

            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:templates' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

{% endblock body %}

crm/templates/documents/view-document.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} {{instance.title}} {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}


    <div class="container">
        <div class="card">
            <div class="card-body">
                {{instance.body|safe}}

                <div class="d-print-none">
                    <div class="float-right">
                        <a href="{% url 'crm:documents' %}"
                            class="btn btn-outline-secondary waves-effect waves-light"><i class="fa fa-arrow-left"></i>
                            Back</a>
                        <a href="javascript:window.print()" class="btn btn-dark waves-effect waves-light"><i
                                class="fa fa-print"></i></a>

                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock body %}

crm/templates/documents/view-template.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} {{instance.title}} {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}


    <div class="container">
        <div class="card">
            <div class="card-body">
                {{instance.body|safe}}

                <div class="d-print-none">
                    <div class="float-right">
                        <a href="{% url 'crm:templates' %}"
                            class="btn btn-outline-secondary waves-effect waves-light"><i class="fa fa-arrow-left"></i>
                            Back</a>
                        <a href="javascript:window.print()" class="btn btn-dark waves-effect waves-light"><i
                                class="fa fa-print"></i></a>

                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock body %}