crm/config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('crm.urls', 'crm'), namespace='crm')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/crm/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', login, name='login'),
    path('logout', logout, name='logout'),
    
    
    path('dashboard', dashboard, name='dashboard'),
    path('dashbaord/contacts', dashboardContacts, name='dashboard-contacts'),
    path('dashbaord/invoices', dashboardInvoices, name='dashboard-invoices'),
    path('dashbaord/quotes', dashboardQuotes, name='dashboard-quotes'),
    path('dashbaord/statistics', dashboardStatistics, name='dashboard-statistics'),
    path('dashbaord/monthlysale', dashboardMonthlySale, name='dashboard-monthlysale'),
    
    
    path('profile', profile, name='profile'),
    
    
    path('staff', users, name='staff-users'),
    path('staff/add', addUser, name='add-staff-user'),
    path('staff/update/<int:id>', updateUser, name='update-staff-user'),
    path('staff/delete/<int:id>', deleteUser, name='delete-staff-user'),
    
    
    path('roles', roles, name='roles'),
    path('role/add', addRole, name='add-role'),
    path('role/update/<int:id>', updateRole, name='update-role'),
    path('role/delete/<int:id>', deleteRole, name='delete-role'),
    
    
    path('category/company', companyCategories, name='company-categories'),
    path('category/company/update/<int:pk>', updateCompanyCategory, name='update-company-category'),
    path('category/company/delete/<int:pk>', deleteCompanyCategory, name='delete-company-category'),
    
    
    path('category/event', eventCategories, name='event-categories'),
    path('category/event/update/<int:pk>', updateEventCategory, name='update-event-category'),
    path('category/event/delete/<int:pk>', deleteEventCategory, name='delete-event-category'),
    
    
    path('companies', companies, name='companies'),
    path('company/add', addCompany, name='add-company'),
    path('company/update/<int:pk>', updateCompany, name='update-company'),
    path('company/delete/<int:pk>', deleteCompany, name='delete-company'),
    
    
    path('contacts', contacts, name='contacts'),
    path('contact/add', addContact, name='add-contact'),
    path('contact/update/<int:pk>', updateContact, name='update-contact'),
    path('contact/delete/<int:pk>', deleteContact, name='delete-contact'),
    
    
    path('circles', circles, name='circles'),
    path('circle/update/<int:pk>', updateCircle, name='update-circle'),
    path('circle/delete/<int:pk>', deleteCircle, name='delete-circle'),
    
    
    path('events', events, name='events'),
    path('event/add', addEvent, name='add-event'),
    path('event/update/<int:pk>', updateEvent, name='update-event'),
    path('event/delete/<int:pk>', deleteEvent, name='delete-event'),
    
    
    path('inbox' , inbox, name='inbox'),
    path('messages/view' , viewMessageAjax, name='view-message'),
    path('messages/sent' , messagesSent, name='sent-messages'),
    path('messages/signatures' , messagesSignature, name='signature-messages'),
    path('messages/trash' , messagesTrash, name='trash-messages'),
    path('message/send' , sendMessage, name='send-message'),
    path('message/delete/<int:pk>' , deleteMessage, name='delete-message'),
    
    
    path('items', items, name='items'),
    path('item/add', addItem, name='add-item'),
    path('item/update/<int:pk>', updateItem, name='update-item'),
    path('item/delete/<int:pk>', deleteItem, name='delete-item'),
    
    
    path('taxes', taxes, name='taxes'),
    path('tax/add', addTax, name='add-tax'),
    path('tax/update/<int:pk>', updateTax, name='update-tax'),
    path('tax/delete/<int:pk>', deleteTax, name='delete-tax'),
    
    
    path('discounts', discounts, name='discounts'),
    path('discount/add', addDiscount, name='add-discount'),
    path('discount/update/<int:pk>', updateDiscount, name='update-discount'),
    path('discount/delete/<int:pk>', deleteDiscount, name='delete-discount'),
    
    
    path('invoice-settings', invoiceSetting, name='invoice-setting'),
    
    path('invoices', invoices, name='invoices'),
    path('invoice/add', addInvoice, name='add-invoice'),
    path('invoice/view/<str:inv_no>', viewInvoice, name='view-invoice'),
    path('invoice/delete/<int:id>', deleteInvoice, name='delete-invoice'),
    
    
    path('estimate-settings', estimateSetting, name='estimate-setting'),
    
    
    path('estimates', estimates, name='estimates'),
    path('estimate/add', addEstimate, name='add-estimate'),
    path('estimate/view/<str:est_no>', viewEstimate, name='view-estimate'),
    path('estimate/delete/<int:id>', deleteEstimate, name='delete-estimate'),
    
    
    path('templates', templates, name='templates'),
    path('template/add', addTemplate, name='add-template'),
    path('template/view/<int:pk>', viewTemplate, name='view-template'),
    path('template/update/<int:pk>', updateTemplate, name='update-template'),
    path('template/delete/<int:pk>', deleteTemplate, name='delete-template'),
    
    
    path('documents', documents, name='documents'),
    path('document/add', addDocument, name='add-document'),
    path('document/view/<int:pk>', viewDocument, name='view-document'),
    path('document/update/<int:pk>', updateDocument, name='update-document'),
    path('document/delete/<int:pk>', deleteDocument, name='delete-document'),
]

crm/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here..
class Profile(models.Model):
    TYPE_CHOICES = (
        (1, 'Admin'),
        (2, 'User'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='users')

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name




class CompanyCategory(models.Model):
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES)
    name = models.CharField(max_length=200)

    class Meta:

        verbose_name = 'Company Category'
        verbose_name_plural = 'Company Categories'

    def __str__(self):
        return self.name
    
    
class EventCategory(models.Model):
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES)
    name = models.CharField(max_length=200)

    class Meta:

        verbose_name = 'Event Category'
        verbose_name_plural = 'Event Categories'

    def __str__(self):
        return self.name



class Company(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to="company/logo", null=True, blank=True)
    category = models.ForeignKey(CompanyCategory, on_delete=models.CASCADE)
    background_info = models.TextField()
    phone_number = models.CharField(max_length=100)
    website = models.URLField(null=True, blank=True)
    skype = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    zip_code = models.IntegerField()
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    
    class Meta:

        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name


class Contact(models.Model):
    ROLE_CHOICES = (
        (1, 'Lead'),
        (2, 'Prospect'),
        (3, 'Client'),
    )
    NAME_PREFIX_CHOICES = (
        ('Mr.', 'Mr.'),
        ('Ms.', 'Ms.'),
        ('Mrs.', 'Mrs.'),
        ('Miss.', 'Miss.'),
        ('Mx.', 'Mx'),
        ('Dr.', 'Dr.'),
    )
    
    role = models.IntegerField(choices=ROLE_CHOICES)
    name_prefix = models.CharField(max_length=5, choices=NAME_PREFIX_CHOICES)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    avatar = models.ImageField(upload_to="contacts", null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    designation = models.CharField(max_length=200)
    background_info = models.TextField()
    phone_number = models.CharField(max_length=100)
    website = models.URLField(null=True, blank=True)
    skype = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    zip_code = models.IntegerField()
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    

    class Meta:

        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    def __str__(self):
        return self.first_name + ' ' + self.last_name



class Circle(models.Model):
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES)
    name = models.CharField(max_length=100)
    description = models.TextField()
    color = models.CharField(max_length=100)
    

    class Meta:

        verbose_name = 'Circle'
        verbose_name_plural = 'Circles'

    def __str__(self):
        return self.name


class CircleClient(models.Model):
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE, related_name='circle_contact')
    client = models.ForeignKey(Contact, on_delete=models.CASCADE)

    class Meta:

        verbose_name = 'Circle Client'
        verbose_name_plural = 'Circle Clients'

    def __str__(self):
        return self.circle.name + ' (' + self.client.first_name + ' ' + self.client.last_name + ")"
    
    

class Event(models.Model):
    VISIBILITY_CHOICES = (
        (1, 'Public'),
        (2, 'Private'),
    )
    DURATION_CHOICES = (
        ('15 minutes', '15 minutes'),
        ('30 minutes', '30 minutes'),
        ('45 minutes', '45 minutes'),
        ('1 hour', '1 hour'),
        ('1 hour 15 minutes', '1 hour 15 minutes'),
        ('1 hour 30 minutes', '1 hour 30 minutes'),
        ('1 hour 45 minutes', '1 hour 45 minutes'),
        ('2 hour', '2 hour'),
        ('2 hours 15 minutes', '2 hours 15 minutes'),
        ('2 hours 30 minutes', '2 hours 30 minutes'),
        ('2 hours 45 minutes', '2 hours 45 minutes'),
        ('3 hour', '3 hour'),
        ('3 hours 15 minutes', '3 hours 15 minutes'),
        ('3 hours 30 minutes', '3 hours 30 minutes'),
        ('3 hours 45 minutes', '3 hours 45 minutes'),
        ('4 hour', '4 hour'),
        ('4 hours 15 minutes', '4 hours 15 minutes'),
        ('4 hours 30 minutes', '4 hours 30 minutes'),
        ('4 hours 45 minutes', '4 hours 45 minutes'),
        ('5 hour', '5 hour'),
        ('5 hours 15 minutes', '5 hours 15 minutes'),
        ('5 hours 30 minutes', '5 hours 30 minutes'),
        ('5 hours 45 minutes', '5 hours 45 minutes'),
        ('6 hour', '6 hour'),
        ('6 hours 15 minutes', '6 hours 15 minutes'),
        ('6 hours 30 minutes', '6 hours 30 minutes'),
        ('6 hours 45 minutes', '6 hours 45 minutes'),
        ('7 hour', '7 hour'),
        ('7 hours 15 minutes', '7 hours 15 minutes'),
        ('7 hours 30 minutes', '7 hours 30 minutes'),
        ('7 hours 45 minutes', '7 hours 45 minutes'),
        ('8 hour', '8 hour'),
        ('8 hours 15 minutes', '8 hours 15 minutes'),
        ('8 hours 30 minutes', '8 hours 30 minutes'),
        ('8 hours 45 minutes', '8 hours 45 minutes'),
        ('9 hour', '9 hour'),
        ('9 hours 15 minutes', '9 hours 15 minutes'),
        ('9 hours 30 minutes', '9 hours 30 minutes'),
        ('9 hours 45 minutes', '9 hours 45 minutes'),
        ('10 hour', '10 hour'),
        ('10 hours 15 minutes', '10 hours 15 minutes'),
        ('10 hours 30 minutes', '10 hours 30 minutes'),
        ('10 hours 45 minutes', '10 hours 45 minutes'),
        ('11 hour', '11 hour'),
        ('11 hours 15 minutes', '11 hours 15 minutes'),
        ('11 hours 30 minutes', '11 hours 30 minutes'),
        ('11 hours 45 minutes', '11 hours 45 minutes'),
        ('12 hour', '12 hour'),
    )
    
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES)
    title = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    duration = models.CharField(max_length=100, choices=DURATION_CHOICES)
    description = models.TextField()
    
    class Meta:

        verbose_name = 'Event'
        verbose_name_plural = 'Events'

    def __str__(self):
        return self.title



class Message(models.Model):
    is_read = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    subject = models.CharField(max_length=500)
    body =  RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
    
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.subject
    
    
class MessageReciever(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="recievers")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:

        verbose_name = 'Message Reciever'
        verbose_name_plural = 'Message Recievers'

    def __str__(self):
        return self.message.subject


class MessageAttachment(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="attachments")
    file = models.FileField(upload_to='attachments/', null=True, blank=True)

    class Meta:

        verbose_name = 'Message Attachment'
        verbose_name_plural = 'Message Attachments'

    def __str__(self):
        return self.message.subject







class Item(models.Model):
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    name = models.CharField(max_length=200)
    developer = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    issue_date = models.DateField()
    verify_institute = models.CharField(max_length=100)
    link_to_verification_certificate = models.URLField()
    description = models.TextField(null=True, blank=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2)

    class Meta:

        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.name
    
    
    
class Tax(models.Model):
    STATUS_CHOICES = (
        (1, 'Active'),
        (2, 'Inactive'),
    )
    
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    percentage = models.IntegerField()

    class Meta:

        verbose_name = 'Tax'
        verbose_name_plural = 'Taxes'


crm/templates/events/add-event.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Add Event {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Add Event</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Visibility</h4><br>
                    <p>Set visibility of your event</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.visibility | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Event Info</h4><br>
                    <p>Add basic event info like title and description of event.</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                    {{form.description | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Time and Date</h4><br>
                    <p>Set time, date, and duration of the event.</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.date | as_crispy_field}}
                    {{form.time | as_crispy_field}}
                    {{form.duration | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:events' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

{% endblock body %}

crm/templates/events/events.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} Events {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">Events</h2>
        </div>
    </div>

    <div class="card card-body">
        {% if perms.crm.add_event %}
        <div class="table-header">
            <a href="{% url 'crm:add-event' %}" class="btn btn-outline-primary mb-4 float-right"><i class="fa fa-plus"></i>&nbsp Add New</a>
        </div>
        {% endif %}


        {% if events|length %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="thead-inverse">
                    <tr class="text-center">
                        <th width="5%">#</th>
                        <th width="30%" class="text-left">Title</th>
                        <th width="10%">Date</th>
                        <th width="10%">Time</th>
                        <th width="10%">Duration</th>
                        <th width="10%">Visibility</th>
                        <th width="10%">Options</th>
                    </tr>
                </thead>
                <tbody>

                    {% for i in events %}
                    <tr class="text-center">
                        <td scope="row">{{forloop.counter}}</td>
                        <td class="text-left">{{i.title | title}} </td>
                        <td>{{i.date | title}}</td>
                        <td>{{i.time | title}}</td>
                        <td>{{i.get_duration_display | title}}</td>
                        <td>

                            {% if i.visibility == 1 %}
                            <span class="badge badge-success">{{i.get_visibility_display}}</span>
                            {% else %}
                            <span class="badge badge-danger">{{i.get_visibility_display}}</span>
                            {% endif %}

                        </td>
                        <td>
                            {% if perms.crm.change_event %}
                            <a href="{% url 'crm:update-event' i.id %}" class="mr-1 text-success"><i class="fa fa-pencil"></i></a>
                            {% endif %}
                            {% if perms.crm.delete_event %}
                            <a href="{% url 'crm:delete-event' i.id %}" class="mr-1 text-danger"><i class="fa fa-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        {% else %}
        <div class="card-header text-center">
            <h4>No record found</h4>
        </div>
        {% endif %}

    </div>
</div>

{% endblock body %}

crm/templates/events/update-event.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}

{% block title %} {{event.title | title}} {% endblock title %}


{% block body %}

<div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert"><strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">
        <div class="card-body">
            <h2 class="">{{event.title | title}}</h2>
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Visibility</h4><br>
                    <p>Set visibility of your event</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.visibility | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Event Info</h4><br>
                    <p>Add basic event info like title and description of event.</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.title | as_crispy_field}}
                    {{form.description | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h4>Time and Date</h4><br>
                    <p>Set time, date, and duration of the event.</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    {{form.date | as_crispy_field}}
                    {{form.time | as_crispy_field}}
                    {{form.duration | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-right">
                        <a href="{% url 'crm:events' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


</div>

{% endblock body %}